
[build]
  publish = "dist"
  functions = "api/netlify"
  command = "yarn build && cd api/netlify && yarn build"

# Dev doesn't work yet. Any takers?
# [dev]  
  # command = "npm run dev:ssr"
  # targetPort = 5000
  # publish = "assets"
  # autoLaunch = true

[[redirects]]  
  # SPA only
  from = "/*"
  to = "/__app.html"
  status = 200